spring.application.name=u5-w2-d5
spring.datasource.url=jdbc:postgresql://localhost:5432/u5-w2-d5
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate
spring.jpa.hibernate.ddl-auto=update